#!/bin/bash

# Minimal floating badges - Catppuccin Mocha theme

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Colors (ARGB format)
BADGE_BG=0xb01e1e2e          # base, 70% opacity
ICON_COLOR=0xffcba6f7        # mauve (accent)
LABEL_COLOR=0xffcdd6f4       # text

##### Bar Appearance - invisible bar, items float independently #####
sketchybar --bar position=top \
                 height=46 \
                 color=0x00000000 \
                 border_width=0 \
                 margin=0 \
                 y_offset=5 \
                 padding_left=10 \
                 padding_right=10

##### Defaults for floating badges #####
default=(
  icon.font="Hack Nerd Font:Bold:14.0"
  label.font="Hack Nerd Font:Regular:12.0"
  icon.color=$ICON_COLOR
  label.color=$LABEL_COLOR
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=0
  label.padding_right=10
  background.color=$BADGE_BG
  background.corner_radius=15
  background.height=30
  background.drawing=on
  padding_left=5
  padding_right=5
)
sketchybar --default "${default[@]}"

##### Spaces - Left Side (clickable) #####
INACTIVE_COLOR=0xff6c7086   # overlay0

# Key codes for numbers 1-5 (used for Ctrl+N shortcuts)
KEY_CODES=(18 19 20 21 23)

for i in 1 2 3 4 5
do
  idx=$((i-1))
  keycode=${KEY_CODES[$idx]}
  sketchybar --add space space.$i left \
             --set space.$i space=$i \
                            icon=$i \
                            icon.padding_left=12 \
                            icon.padding_right=12 \
                            label.drawing=off \
                            icon.color=$INACTIVE_COLOR \
                            script="$PLUGIN_DIR/space.sh" \
                            click_script="osascript -e 'tell application \"System Events\" to key code $keycode using control down'"
done

##### Floating Badges - Right Side #####

# CPU Badge
sketchybar --add item cpu right \
           --set cpu update_freq=3 \
                     script="$PLUGIN_DIR/cpu.sh" \
                     click_script="open -a 'Activity Monitor'"

# RAM Badge
sketchybar --add item ram right \
           --set ram update_freq=5 \
                     script="$PLUGIN_DIR/ram.sh" \
                     click_script="open -a 'Activity Monitor'"

##### Finalize #####
sketchybar --update
