#!/bin/bash

# Catppuccin Mocha theme for SketchyBar

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Colors (ARGB format)
BAR_COLOR=0xb01e1e2e        # base, 70% opacity
ICON_COLOR=0xffcdd6f4       # text
LABEL_COLOR=0xffcdd6f4      # text
ACCENT_COLOR=0xffcba6f7     # mauve
HIGHLIGHT_BG=0xff45475a     # surface1
INACTIVE_COLOR=0xff6c7086   # overlay0

##### Bar Appearance #####
sketchybar --bar position=top \
                 height=36 \
                 blur_radius=30 \
                 color=$BAR_COLOR \
                 border_width=0 \
                 margin=10 \
                 y_offset=5 \
                 corner_radius=10 \
                 padding_left=10 \
                 padding_right=10

##### Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:15.0"
  label.font="Hack Nerd Font:Regular:13.0"
  icon.color=$ICON_COLOR
  label.color=$LABEL_COLOR
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Spaces #####
SPACE_ICONS=("1" "2" "3" "4" "5")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=8
    icon.padding_right=8
    icon.color=$INACTIVE_COLOR
    background.color=$HIGHLIGHT_BG
    background.corner_radius=6
    background.height=24
    background.drawing=off
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Left Items #####
sketchybar --add item front_app left \
           --set front_app icon.drawing=off \
                          label.color=$ACCENT_COLOR \
                          label.font="Hack Nerd Font:Bold:13.0" \
                          script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

# Running Apps Anchor (individual app items are added dynamically after this)
sketchybar --add item running_apps left \
           --set running_apps icon.drawing=off \
                              label.drawing=off \
                              padding_left=0 \
                              padding_right=0 \
                              update_freq=3 \
                              script="$PLUGIN_DIR/apps.sh" \
           --subscribe running_apps front_app_switched space_change

##### Right Items #####

# Clock (click to open Calendar)
sketchybar --add item clock right \
           --set clock update_freq=10 \
                       icon.drawing=off \
                       label.color=$LABEL_COLOR \
                       script="$PLUGIN_DIR/clock.sh" \
                       click_script="open -a 'Calendar'"

# CPU (click to open Activity Monitor)
sketchybar --add item cpu right \
           --set cpu update_freq=3 \
                     icon.color=$ACCENT_COLOR \
                     label.color=$LABEL_COLOR \
                     script="$PLUGIN_DIR/cpu.sh" \
                     click_script="open -a 'Activity Monitor'"

# Battery (click to open Battery settings)
sketchybar --add item battery right \
           --set battery update_freq=120 \
                         icon.color=$ACCENT_COLOR \
                         script="$PLUGIN_DIR/battery.sh" \
                         click_script="open 'x-apple.systempreferences:com.apple.preference.battery'" \
           --subscribe battery system_woke power_source_change

# Volume (click to open Sound settings)
sketchybar --add item volume right \
           --set volume icon.color=$ACCENT_COLOR \
                        script="$PLUGIN_DIR/volume.sh" \
                        click_script="open 'x-apple.systempreferences:com.apple.preference.sound'" \
           --subscribe volume volume_change

##### Finalize #####
sketchybar --update
