########################################
# The Icebergs
# Frederic Edwin Church, 1861
# deep teal water, glacial ice, dusk sky
########################################

background = #101a19
background-opacity = 0.85
background-blur-radius = 30

foreground = #e8e0d4

cursor-color = #d3a778
cursor-text = #101a19
adjust-cursor-thickness = 60

selection-background = #2e403d
selection-foreground = #e8e0d4

# ANSI Palette
palette = 0=#182422
palette = 1=#c76f5c
palette = 2=#63a68f
palette = 3=#d3a778
palette = 4=#85a5b5
palette = 5=#bd8f95
palette = 6=#83b8b0
palette = 7=#d9d2c5

palette = 8=#6e8380
palette = 9=#dc8a75
palette = 10=#7fc0a8
palette = 11=#e5bd92
palette = 12=#a2bfcd
palette = 13=#d3a9ae
palette = 14=#a1d0c8
palette = 15=#f2ece1
