########################################
# Voltage
# neutral black, electric blue accent, saturated ansi
########################################

background = #0a0a0a
background-opacity = 0.85
background-blur-radius = 30

foreground = #fafafa

cursor-color = #b4cbff
cursor-text = #0a0a0a
adjust-cursor-thickness = 60

selection-background = #19283c
selection-foreground = #fafafa

# ANSI Palette
palette = 0=#171717
palette = 1=#ff2e3f
palette = 2=#0dbe4e
palette = 3=#ffca00
palette = 4=#009fff
palette = 5=#e130ac
palette = 6=#08c0ef
palette = 7=#bcbcbc

palette = 8=#171717
palette = 9=#ff2e3f
palette = 10=#86c427
palette = 11=#ffca00
palette = 12=#009fff
palette = 13=#e130ac
palette = 14=#08c0ef
palette = 15=#bcbcbc
