-- Icebergs
-- colors lifted from Frederic Edwin Church, "The Icebergs" (1861)
-- same palette as the ghostty and vscode setups in this repo

local p = {
  bg = "#101a19",
  bg1 = "#182422",
  line = "#15201e",
  sel = "#2e403d",
  border = "#3a4f4b",
  fg = "#e8e0d4",
  white = "#d9d2c5",
  bright = "#f2ece1",
  dim = "#6e8380",
  red = "#c76f5c",
  red1 = "#dc8a75",
  green = "#63a68f",
  green1 = "#7fc0a8",
  amber = "#d3a778",
  amber1 = "#e5bd92",
  blue = "#85a5b5",
  blue1 = "#a2bfcd",
  rose = "#bd8f95",
  rose1 = "#d3a9ae",
  cyan = "#83b8b0",
  cyan1 = "#a1d0c8",
  -- diff surfaces, hand mixed toward bg
  diff_add = "#1a2e27",
  diff_del = "#2c201d",
  diff_mod = "#28251d",
  diff_txt = "#3b3323",
}

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.termguicolors = true
vim.g.colors_name = "icebergs"

-- transparent Normal so ghostty's blur shows through, same trick as vscode vibrancy
local groups = {
  Normal = { fg = p.fg, bg = "NONE" },
  NormalNC = { link = "Normal" },
  NormalFloat = { fg = p.fg, bg = p.bg1 },
  FloatBorder = { fg = p.border, bg = p.bg1 },
  FloatTitle = { fg = p.amber, bg = p.bg1, bold = true },
  WinSeparator = { fg = p.sel },
  EndOfBuffer = { fg = p.bg1 },
  NonText = { fg = p.sel },
  Whitespace = { fg = p.sel },
  SignColumn = { fg = p.dim, bg = "NONE" },
  LineNr = { fg = p.dim },
  CursorLineNr = { fg = p.amber, bold = true },
  CursorLine = { bg = p.line },
  CursorColumn = { bg = p.line },
  ColorColumn = { bg = p.line },
  Visual = { bg = p.sel },
  VisualNOS = { bg = p.sel },
  Search = { fg = p.bg, bg = p.amber },
  IncSearch = { fg = p.bg, bg = p.red1 },
  CurSearch = { link = "IncSearch" },
  MatchParen = { fg = p.amber1, bold = true, underline = true },
  Folded = { fg = p.dim, bg = p.bg1 },
  FoldColumn = { fg = p.dim },
  Directory = { fg = p.blue },
  Title = { fg = p.blue1, bold = true },
  ErrorMsg = { fg = p.red },
  WarningMsg = { fg = p.amber },
  MoreMsg = { fg = p.green },
  Question = { fg = p.blue },
  ModeMsg = { fg = p.white },
  QuickFixLine = { bg = p.sel },
  SpellBad = { sp = p.red, undercurl = true },
  SpellCap = { sp = p.amber, undercurl = true },
  SpellLocal = { sp = p.cyan, undercurl = true },
  SpellRare = { sp = p.rose, undercurl = true },

  Pmenu = { fg = p.white, bg = p.bg1 },
  PmenuSel = { fg = p.bright, bg = p.sel },
  PmenuSbar = { bg = p.bg1 },
  PmenuThumb = { bg = p.sel },
  WildMenu = { link = "PmenuSel" },

  StatusLine = { fg = p.white, bg = p.bg1 },
  StatusLineNC = { fg = p.dim, bg = p.bg1 },
  TabLine = { fg = p.dim, bg = p.bg1 },
  TabLineFill = { bg = p.bg1 },
  TabLineSel = { fg = p.fg, bg = p.sel },
  WinBar = { fg = p.white, bg = "NONE" },
  WinBarNC = { fg = p.dim, bg = "NONE" },

  -- syntax
  Comment = { fg = p.dim, italic = true },
  Constant = { fg = p.amber1 },
  String = { fg = p.green },
  Character = { fg = p.green1 },
  Number = { fg = p.amber1 },
  Boolean = { fg = p.amber1 },
  Float = { fg = p.amber1 },
  Identifier = { fg = p.fg },
  Function = { fg = p.blue1 },
  Statement = { fg = p.rose },
  Conditional = { fg = p.rose },
  Repeat = { fg = p.rose },
  Label = { fg = p.rose },
  Operator = { fg = p.white },
  Keyword = { fg = p.rose },
  Exception = { fg = p.red },
  PreProc = { fg = p.cyan },
  Include = { fg = p.rose },
  Define = { fg = p.cyan },
  Macro = { fg = p.red1 },
  Type = { fg = p.cyan },
  StorageClass = { fg = p.cyan },
  Structure = { fg = p.cyan },
  Typedef = { fg = p.cyan },
  Special = { fg = p.cyan1 },
  SpecialChar = { fg = p.cyan1 },
  Tag = { fg = p.blue },
  Delimiter = { fg = p.dim },
  SpecialComment = { fg = p.dim, bold = true },
  Debug = { fg = p.red1 },
  Underlined = { fg = p.cyan, underline = true },
  Error = { fg = p.red },
  Todo = { fg = p.bg, bg = p.amber, bold = true },

  -- treesitter
  ["@variable"] = { fg = p.fg },
  ["@variable.builtin"] = { fg = p.red1 },
  ["@variable.parameter"] = { fg = p.fg, italic = true },
  ["@variable.member"] = { fg = p.cyan1 },
  ["@property"] = { fg = p.cyan1 },
  ["@constant"] = { fg = p.amber1 },
  ["@constant.builtin"] = { fg = p.red1 },
  ["@constant.macro"] = { fg = p.red1 },
  ["@module"] = { fg = p.fg },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = p.cyan1 },
  ["@string.regexp"] = { fg = p.green1 },
  ["@string.special.url"] = { fg = p.cyan, underline = true },
  ["@character"] = { link = "Character" },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = p.cyan },
  ["@attribute"] = { fg = p.amber },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { fg = p.blue1 },
  ["@function.macro"] = { fg = p.red1 },
  ["@function.method"] = { link = "Function" },
  ["@constructor"] = { fg = p.cyan },
  ["@operator"] = { link = "Operator" },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.function"] = { fg = p.rose },
  ["@keyword.return"] = { fg = p.rose1 },
  ["@keyword.import"] = { fg = p.rose },
  ["@punctuation.delimiter"] = { fg = p.dim },
  ["@punctuation.bracket"] = { fg = p.white },
  ["@punctuation.special"] = { fg = p.cyan1 },
  ["@comment"] = { link = "Comment" },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.error"] = { fg = p.bg, bg = p.red, bold = true },
  ["@comment.warning"] = { fg = p.bg, bg = p.amber, bold = true },
  ["@comment.note"] = { fg = p.bg, bg = p.blue, bold = true },
  ["@tag"] = { fg = p.blue },
  ["@tag.builtin"] = { fg = p.blue },
  ["@tag.attribute"] = { fg = p.amber },
  ["@tag.delimiter"] = { fg = p.dim },
  ["@markup.heading"] = { fg = p.blue1, bold = true },
  ["@markup.heading.1"] = { fg = p.amber1, bold = true },
  ["@markup.heading.2"] = { fg = p.blue1, bold = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.quote"] = { fg = p.dim, italic = true },
  ["@markup.link"] = { fg = p.cyan },
  ["@markup.link.url"] = { fg = p.cyan, underline = true },
  ["@markup.link.label"] = { fg = p.blue },
  ["@markup.raw"] = { fg = p.green },
  ["@markup.list"] = { fg = p.amber },
  ["@diff.plus"] = { fg = p.green },
  ["@diff.minus"] = { fg = p.red },
  ["@diff.delta"] = { fg = p.amber },

  -- diagnostics
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.amber },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan },
  DiagnosticOk = { fg = p.green },
  DiagnosticUnderlineError = { sp = p.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.amber, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.cyan, undercurl = true },
  DiagnosticVirtualTextError = { fg = p.red },
  DiagnosticVirtualTextWarn = { fg = p.amber },
  DiagnosticVirtualTextInfo = { fg = p.blue },
  DiagnosticVirtualTextHint = { fg = p.cyan },
  LspReferenceText = { bg = p.sel },
  LspReferenceRead = { bg = p.sel },
  LspReferenceWrite = { bg = p.sel },
  LspInlayHint = { fg = p.dim, italic = true },

  -- diff / git
  DiffAdd = { bg = p.diff_add },
  DiffDelete = { fg = p.red, bg = p.diff_del },
  DiffChange = { bg = p.diff_mod },
  DiffText = { bg = p.diff_txt },
  Added = { fg = p.green },
  Removed = { fg = p.red },
  Changed = { fg = p.amber },
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.amber },
  GitSignsDelete = { fg = p.red },

  -- plugins
  TelescopeBorder = { fg = p.border },
  TelescopeTitle = { fg = p.amber, bold = true },
  TelescopeSelection = { bg = p.sel },
  TelescopeMatching = { fg = p.amber1, bold = true },
  NeoTreeNormal = { fg = p.fg, bg = "NONE" },
  NeoTreeNormalNC = { fg = p.fg, bg = "NONE" },
  NeoTreeDirectoryIcon = { fg = p.blue },
  NeoTreeDirectoryName = { fg = p.blue },
  NeoTreeRootName = { fg = p.amber, bold = true },
  NeoTreeGitModified = { fg = p.amber },
  NeoTreeGitAdded = { fg = p.green },
  NeoTreeGitDeleted = { fg = p.red },
  WhichKey = { fg = p.cyan },
  WhichKeyGroup = { fg = p.blue },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.dim },
  LazyH1 = { fg = p.bg, bg = p.amber, bold = true },
  LazyButton = { fg = p.white, bg = p.bg1 },
  LazyButtonActive = { fg = p.bright, bg = p.sel, bold = true },
  LazySpecial = { fg = p.cyan },
  NotifyBackground = { bg = p.bg },
  FlashLabel = { fg = p.bg, bg = p.red1, bold = true },
  FlashMatch = { bg = p.sel },
  SnacksIndent = { fg = p.bg1 },
  SnacksIndentScope = { fg = p.sel },
  SnacksPickerDir = { fg = p.dim },
  SnacksPickerMatch = { fg = p.amber1, bold = true },
  IblIndent = { fg = p.bg1 },
  IblScope = { fg = p.sel },
  BufferLineFill = { bg = "NONE" },
  AlphaHeader = { fg = p.cyan },
  SnacksDashboardHeader = { fg = p.cyan },
  SnacksDashboardIcon = { fg = p.blue },
  SnacksDashboardDesc = { fg = p.fg },
  SnacksDashboardKey = { fg = p.amber },
  SnacksDashboardFooter = { fg = p.dim, italic = true },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

-- :terminal matches the ghostty palette exactly
local term = {
  "#182422", "#c76f5c", "#63a68f", "#d3a778",
  "#85a5b5", "#bd8f95", "#83b8b0", "#d9d2c5",
  "#6e8380", "#dc8a75", "#7fc0a8", "#e5bd92",
  "#a2bfcd", "#d3a9ae", "#a1d0c8", "#f2ece1",
}
for i, color in ipairs(term) do
  vim.g["terminal_color_" .. (i - 1)] = color
end
