-- Voltage
-- neutral black, electric blue accent, saturated syntax
-- same palette as the ghostty and vscode setups in this repo

local p = {
  bg = "#0a0a0a",
  bg1 = "#171717",
  line = "#111111",
  sel = "#19283c",
  border = "#262626",
  fg = "#fafafa",
  white = "#a3a3a3",
  bright = "#ffffff",
  dim = "#737373",
  red = "#ff2e3f",
  red1 = "#ff855e",
  green = "#5ecc71",
  green1 = "#60d199",
  amber = "#ffca00",
  amber1 = "#ffd452",
  blue = "#009fff",
  blue1 = "#9d6afb",
  rose = "#ff678d",
  rose1 = "#ff678d",
  cyan = "#d568ea",
  cyan1 = "#08c0ef",
  -- diff surfaces, hand mixed toward bg
  -- extra syntax slots
  number = "#68cdf2",
  variable = "#ffa359",
  builtin = "#ffab16",
  param = "#a3a3a3",
  punct = "#636363",
  attr = "#60d199",
  regex = "#64d1db",
  escape = "#61d5c0",
  decorator = "#69b1ff",
  diff_add = "#0f2a1c",
  diff_del = "#2a1013",
  diff_mod = "#2a2410",
  diff_txt = "#3a3412",
}

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.termguicolors = true
vim.g.colors_name = "voltage"

-- transparent Normal so ghostty blur shows through
local groups = {
  Normal = { fg = p.fg, bg = "NONE" },
  NormalNC = { link = "Normal" },
  NormalFloat = { fg = p.fg, bg = p.bg1 },
  FloatBorder = { fg = p.border, bg = p.bg1 },
  FloatTitle = { fg = p.blue, bg = p.bg1, bold = true },
  WinSeparator = { fg = p.sel },
  EndOfBuffer = { fg = p.bg1 },
  NonText = { fg = p.sel },
  Whitespace = { fg = p.sel },
  SignColumn = { fg = p.dim, bg = "NONE" },
  LineNr = { fg = p.dim },
  CursorLineNr = { fg = p.white, bold = true },
  CursorLine = { bg = p.line },
  CursorColumn = { bg = p.line },
  ColorColumn = { bg = p.line },
  Visual = { bg = p.sel },
  VisualNOS = { bg = p.sel },
  Search = { fg = p.bg, bg = p.blue },
  IncSearch = { fg = p.bg, bg = p.amber },
  CurSearch = { link = "IncSearch" },
  MatchParen = { fg = p.blue, bold = true, underline = true },
  Folded = { fg = p.dim, bg = p.bg1 },
  FoldColumn = { fg = p.dim },
  Directory = { fg = p.blue },
  Title = { fg = p.blue1, bold = true },
  ErrorMsg = { fg = p.red },
  WarningMsg = { fg = p.amber },
  MoreMsg = { fg = p.green },
  Question = { fg = p.blue },
  ModeMsg = { fg = p.white },
  QuickFixLine = { bg = p.sel },
  SpellBad = { sp = p.red, undercurl = true },
  SpellCap = { sp = p.amber, undercurl = true },
  SpellLocal = { sp = p.cyan1, undercurl = true },
  SpellRare = { sp = p.rose, undercurl = true },

  Pmenu = { fg = p.white, bg = p.bg1 },
  PmenuSel = { fg = p.bright, bg = p.sel },
  PmenuSbar = { bg = p.bg1 },
  PmenuThumb = { bg = p.sel },
  WildMenu = { link = "PmenuSel" },

  StatusLine = { fg = p.white, bg = p.bg1 },
  StatusLineNC = { fg = p.dim, bg = p.bg1 },
  TabLine = { fg = p.dim, bg = p.bg1 },
  TabLineFill = { bg = p.bg1 },
  TabLineSel = { fg = p.fg, bg = p.sel },
  WinBar = { fg = p.white, bg = "NONE" },
  WinBarNC = { fg = p.dim, bg = "NONE" },

  -- syntax
  Comment = { fg = p.dim, italic = true },
  Constant = { fg = p.amber1 },
  String = { fg = p.green },
  Character = { fg = p.green },
  Number = { fg = p.number },
  Boolean = { fg = p.number },
  Float = { fg = p.number },
  Identifier = { fg = p.variable },
  Function = { fg = p.blue1 },
  Statement = { fg = p.rose },
  Conditional = { fg = p.rose },
  Repeat = { fg = p.rose },
  Label = { fg = p.rose },
  Operator = { fg = p.cyan1 },
  Keyword = { fg = p.rose },
  Exception = { fg = p.red },
  PreProc = { fg = p.rose },
  Include = { fg = p.rose },
  Define = { fg = p.rose },
  Macro = { fg = p.builtin },
  Type = { fg = p.cyan },
  StorageClass = { fg = p.cyan },
  Structure = { fg = p.cyan },
  Typedef = { fg = p.cyan },
  Special = { fg = p.escape },
  SpecialChar = { fg = p.escape },
  Tag = { fg = p.red1 },
  Delimiter = { fg = p.punct },
  SpecialComment = { fg = p.dim, bold = true },
  Debug = { fg = p.red1 },
  Underlined = { fg = p.blue, underline = true },
  Error = { fg = p.red },
  Todo = { fg = p.bg, bg = p.amber1, bold = true },

  -- treesitter
  ["@variable"] = { fg = p.variable },
  ["@variable.builtin"] = { fg = p.builtin },
  ["@variable.parameter"] = { fg = p.param },
  ["@variable.member"] = { fg = p.variable },
  ["@property"] = { fg = p.variable },
  ["@constant"] = { fg = p.amber1 },
  ["@constant.builtin"] = { fg = p.number },
  ["@constant.macro"] = { fg = p.builtin },
  ["@module"] = { fg = p.builtin },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { fg = p.escape },
  ["@string.regexp"] = { fg = p.regex },
  ["@string.special.url"] = { fg = p.blue, underline = true },
  ["@character"] = { link = "Character" },
  ["@number"] = { link = "Number" },
  ["@boolean"] = { link = "Boolean" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { fg = p.cyan },
  ["@attribute"] = { fg = p.decorator },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { fg = p.blue1 },
  ["@function.macro"] = { fg = p.blue1 },
  ["@function.method"] = { link = "Function" },
  ["@constructor"] = { fg = p.cyan },
  ["@operator"] = { link = "Operator" },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.function"] = { fg = p.rose },
  ["@keyword.return"] = { fg = p.rose },
  ["@keyword.import"] = { fg = p.rose },
  ["@punctuation.delimiter"] = { fg = p.punct },
  ["@punctuation.bracket"] = { fg = p.punct },
  ["@punctuation.special"] = { fg = p.rose },
  ["@comment"] = { link = "Comment" },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.error"] = { fg = p.bg, bg = p.red, bold = true },
  ["@comment.warning"] = { fg = p.bg, bg = p.amber, bold = true },
  ["@comment.note"] = { fg = p.bg, bg = p.cyan1, bold = true },
  ["@tag"] = { fg = p.red1 },
  ["@tag.builtin"] = { fg = p.red1 },
  ["@tag.attribute"] = { fg = p.attr },
  ["@tag.delimiter"] = { fg = p.punct },
  ["@markup.heading"] = { fg = p.red1, bold = true },
  ["@markup.heading.1"] = { fg = p.red1, bold = true },
  ["@markup.heading.2"] = { fg = p.red1, bold = true },
  ["@markup.strong"] = { fg = p.amber1, bold = true },
  ["@markup.italic"] = { fg = p.rose, italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.quote"] = { fg = p.dim, italic = true },
  ["@markup.link"] = { fg = p.rose },
  ["@markup.link.url"] = { fg = p.rose, underline = true },
  ["@markup.link.label"] = { fg = p.blue1 },
  ["@markup.raw"] = { fg = p.green },
  ["@markup.list"] = { fg = p.punct },
  ["@diff.plus"] = { fg = p.green },
  ["@diff.minus"] = { fg = p.red1 },
  ["@diff.delta"] = { fg = p.builtin },

  -- diagnostics
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.amber },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan1 },
  DiagnosticOk = { fg = p.green },
  DiagnosticUnderlineError = { sp = p.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.amber, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.cyan1, undercurl = true },
  DiagnosticVirtualTextError = { fg = p.red },
  DiagnosticVirtualTextWarn = { fg = p.amber },
  DiagnosticVirtualTextInfo = { fg = p.blue },
  DiagnosticVirtualTextHint = { fg = p.cyan1 },
  LspReferenceText = { bg = p.sel },
  LspReferenceRead = { bg = p.sel },
  LspReferenceWrite = { bg = p.sel },
  LspInlayHint = { fg = p.dim, italic = true },

  -- diff / git
  DiffAdd = { bg = p.diff_add },
  DiffDelete = { fg = p.red, bg = p.diff_del },
  DiffChange = { bg = p.diff_mod },
  DiffText = { bg = p.diff_txt },
  Added = { fg = p.green },
  Removed = { fg = p.red },
  Changed = { fg = p.amber },
  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.amber },
  GitSignsDelete = { fg = p.red },

  -- plugins
  TelescopeBorder = { fg = p.border },
  TelescopeTitle = { fg = p.blue, bold = true },
  TelescopeSelection = { bg = p.sel },
  TelescopeMatching = { fg = p.blue, bold = true },
  NeoTreeNormal = { fg = p.fg, bg = "NONE" },
  NeoTreeNormalNC = { fg = p.fg, bg = "NONE" },
  NeoTreeDirectoryIcon = { fg = p.blue },
  NeoTreeDirectoryName = { fg = p.blue },
  NeoTreeRootName = { fg = p.blue, bold = true },
  NeoTreeGitModified = { fg = p.amber },
  NeoTreeGitAdded = { fg = p.green },
  NeoTreeGitDeleted = { fg = p.red },
  WhichKey = { fg = p.blue },
  WhichKeyGroup = { fg = p.blue },
  WhichKeyDesc = { fg = p.fg },
  WhichKeySeparator = { fg = p.dim },
  LazyH1 = { fg = p.bg, bg = p.blue, bold = true },
  LazyButton = { fg = p.white, bg = p.bg1 },
  LazyButtonActive = { fg = p.bright, bg = p.sel, bold = true },
  LazySpecial = { fg = p.blue },
  NotifyBackground = { bg = p.bg },
  FlashLabel = { fg = p.bg, bg = p.amber, bold = true },
  FlashMatch = { bg = p.sel },
  SnacksIndent = { fg = p.bg1 },
  SnacksIndentScope = { fg = p.sel },
  SnacksPickerDir = { fg = p.dim },
  SnacksPickerMatch = { fg = p.blue, bold = true },
  IblIndent = { fg = p.bg1 },
  IblScope = { fg = p.sel },
  BufferLineFill = { bg = "NONE" },
  AlphaHeader = { fg = p.blue },
  SnacksDashboardHeader = { fg = p.blue },
  SnacksDashboardIcon = { fg = p.blue },
  SnacksDashboardDesc = { fg = p.fg },
  SnacksDashboardKey = { fg = p.blue },
  SnacksDashboardFooter = { fg = p.dim, italic = true },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

-- :terminal matches the ghostty palette exactly
local term = {
  "#171717", "#ff2e3f", "#0dbe4e", "#ffca00",
  "#009fff", "#e130ac", "#08c0ef", "#bcbcbc",
  "#171717", "#ff2e3f", "#86c427", "#ffca00",
  "#009fff", "#e130ac", "#08c0ef", "#bcbcbc",
}
for i, color in ipairs(term) do
  vim.g["terminal_color_" .. (i - 1)] = color
end
